/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import mael_logo2 from "../assets/img/logo_portfolio.glb";

export function Model(props) {

    const modelRef = useRef(null);
    const { nodes, materials } = useGLTF(mael_logo2)

    useFrame(() => {
        modelRef.current.rotation.y += 0.003;
    })

    return (
        <group {...props} dispose={null} ref={modelRef}>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text.geometry}
            material={materials['Material.001']}
            position={[0, 0.365, 0]}
            rotation={[1.465, -0.129, 0]}
            scale={[4.689, 4.689, 3.175]}
        />
        <group position={[-2.731, -0.767, -1.005]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_1.geometry}
            material={materials.coeur_b}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_2.geometry}
            material={materials.coeur_r}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_3.geometry}
            material={materials.yeux}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_4.geometry}
            material={materials.jean}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_5.geometry}
            material={materials.sweat}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_6.geometry}
            material={materials.peau}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_7.geometry}
            material={materials.coeur_b2}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_8.geometry}
            material={materials.coeur_o}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_9.geometry}
            material={materials.texte}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_10.geometry}
            material={materials.texte_2}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.figurine_complete001_11.geometry}
            material={materials.cheveux}
            />
        </group>
        </group>
    )
}

useGLTF.preload(mael_logo2)